name: estimpro
description: Estimation immobilière terrain — Faucigny Immobilier by Efficity
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  pdf: ^3.10.8
  uuid: ^4.3.3
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  http: ^1.2.1
  open_file: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
